version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: thaiboxe-db
    environment:
      POSTGRES_USER: thaiboxe
      POSTGRES_PASSWORD: Thaiboxe@123
      POSTGRES_DB: thaiboxe-db
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
